CREATE TABLE [dbo].[Lists]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Name VARChAR(50) NOT NULL,
	IdProject INT NOT NULL,
	DeadLine DATETIME,
	CreationDate DATETIME NOT NULL DEFAULT GETDATE()

	FOREIGN KEY(IdProject) REFERENCES [Projects](Id)
)
