CREATE TABLE [dbo].[Tasks]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Name VARCHAR(50) NOT NULL,
	IdList INT NOT NULL,
	DeadLine DATETIME,
	CreationDate DATETIME DEFAULT GETDATE() NOT NULL

	FOREIGN KEY(IdList) REFERENCES [Lists](Id)
)
