CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Email VARCHAR(100) NOT NULL,
	Password VARCHAR(100) NOT NULL,
	Salt VARCHAR(100) NOT NULL,
	IsActive BIT NOT NULL DEFAULT(1), 
	CreationDate DATETIME NOT NULL DEFAULT GETDATE()
)
